### ISSUE TITLE
USER STORY: Delete Recipe

### ISSUE THREAD

**Issue by dimicoding** [dimicoding/wildflour-blogue#10]
As a user, I want to delete a blog post so that I can remove content that is no longer relevant or necessary.

## Acceptance Criteria
  <ul>
    <li>Acceptance Criteria 1:The user should be able to delete their own blog posts</li>
    <li>Acceptance Criteria 2:The user should be redirected to the homepage after deletion.</li>
    <li>Acceptance Criteria 3: The user should receive a confirmation message before the deletion is processed.</li>
    
  </ul>
  
 # Tasks
  - [x] Add a "Delete" button
  - [x] Implement a confirmation modal to ensure the user wants to delete the blog post.
  - [x] Ensure that the deletion function is restricted to the author of the blog post.
