### ISSUE TITLE
USER STORY: Recipe Categories

### ISSUE THREAD

**Issue by dimicoding** [dimicoding/wildflour-blogue#11]
As a user, I want to be able to store different recipes in separate categories so that I can easily access them based on my needs.

## Acceptance Criteria
  <ul>
    <li>Acceptance Criteria 1: The user should be able to add new recipes to each category</li>
    <li>Acceptance Criteria 2: The user should be able to view a list of all categories and select one to view recipes</li>
    <li>Acceptance Criteria 3: The user should be able to easily navigate between categories and recipes.</li>
    
  </ul>
  
 # Tasks
  - [ ] Implement the ability to add, edit, and delete users' recipes within a category.
  - [x] Implement the ability to look for recipes within a specific category.
  - [x]  Implement the ability to view a recipe category on the new page.
