### ISSUE TITLE
USER STORY: Add the footer section

### ISSUE THREAD

**Issue by dimicoding** [dimicoding/wildflour-blogue#3]
As a user, I want a straightforward footer so that I can easily find the website's links to other categories and social media platforms.

## Acceptance Criteria
  <ul>
    <li>Acceptance Criteria 1: Possible to see on various screens </li>
    <li>Acceptance Criteria 2: Links to other pages and icons for social media</li>
    <li>Acceptance Criteria 3: The user can register to blog's Newslatter</li>
    
  </ul>
  
 # Tasks
  - [x] Adjust media queries and bootstrap classes
  - [x] Links and icons
  - [x] Subscription to newsletter field
