### ISSUE TITLE
USER STORY: Update blog post

### ISSUE THREAD

**Issue by dimicoding** [dimicoding/wildflour-blogue#9]
As a user, I want to be able to easily edit my published blog posts, so that I can correct errors, improve the content and keep my readers engaged.

## Acceptance Criteria
  <ul>
    <li>Acceptance Criteria 1: The user can edit and update their blog posts with ease and efficiency.</li>
    <li>Acceptance Criteria 2: The user can access a list of their published blog posts.</li>
    <li>Acceptance Criteria 3: The user can modify the title, content, and other attributes of the blog post.</li>
    
  </ul>
  
 # Tasks
  - [x] Add a "Edit" button on the list of published blog posts.
  - [x] Allow the user to modify the title, content, and other attributes of the blog post
  - [x] Implement a "Publish" button to allow the user to publish the updated post.
